from hero import hero

import random

def start():
	heroList = []

	
	heroList.append(hero("Abbadon"))
	heroList.append(hero("Alchemist"))
	heroList.append(hero("Axe"))
	heroList.append(hero("Beastmaster"))
	heroList.append(hero("Brewmaster"))
	heroList.append(hero("Bristleback"))
	heroList.append(hero("Centaur Warrunner"))
	heroList.append(hero("Chaos Knight"))
	heroList.append(hero("Clockwerk"))
	heroList.append(hero("Doom"))
	heroList.append(hero("Dragon Knight"))
	heroList.append(hero("Earth Spirit"))
	heroList.append(hero("Earth Shaker"))
	heroList.append(hero("Elder Titan"))
	heroList.append(hero("Huskar"))
	heroList.append(hero("Io"))
	heroList.append(hero("Kunkka"))
	heroList.append(hero("Legion Commander"))
	heroList.append(hero("Lifestealer"))
	heroList.append(hero("Lycan"))
	heroList.append(hero("Magnus"))
	heroList.append(hero("Night Stalker"))
	heroList.append(hero("Omniknight"))
	heroList.append(hero("Pheonix"))
	heroList.append(hero("Pudge"))
	heroList.append(hero("Sand King"))
	heroList.append(hero("Slardar"))
	heroList.append(hero("Spirit Breaker"))
	heroList.append(hero("Sven"))
	heroList.append(hero("Tidehunter"))
	heroList.append(hero("Timbersaw"))
	heroList.append(hero("Tiny"))
	heroList.append(hero("Treant Protector"))
	heroList.append(hero("Tusk"))
	heroList.append(hero("Underlord"))
	heroList.append(hero("Undying"))
	heroList.append(hero("Wraith King"))
	
	heroList.append(hero("Anti Mage"))
	heroList.append(hero("Arc Warden"))
	heroList.append(hero("Bloodseeker"))
	heroList.append(hero("Bounty Hunter"))
	heroList.append(hero("Broodmother"))
	heroList.append(hero("Clinkz"))
	heroList.append(hero("Drow Ranger"))
	heroList.append(hero("Ember Spirit"))
	heroList.append(hero("Faceless Void"))
	heroList.append(hero("Gyrocopter"))
	heroList.append(hero("Juggernaut"))
	heroList.append(hero("Lone Druid"))
	heroList.append(hero("Luna"))
	heroList.append(hero("Medusa"))
	heroList.append(hero("Meepo"))
	heroList.append(hero("Mirana"))
	heroList.append(hero("Monkey King"))
	heroList.append(hero("Morphling"))
	heroList.append(hero("Naga Siren"))
	heroList.append(hero("Nyx Assassin"))
	heroList.append(hero("Pangolier"))
	heroList.append(hero("Phantom Assassin"))
	heroList.append(hero("Phantom Lancer"))
	heroList.append(hero("Razor"))
	heroList.append(hero("Riki"))
	heroList.append(hero("Shadow Fiend"))
	heroList.append(hero("Slark"))
	heroList.append(hero("Sniper"))
	heroList.append(hero("Spectre"))
	heroList.append(hero("Templar Assassin"))
	heroList.append(hero("Terrorblade"))
	heroList.append(hero("Troll Warlord"))
	heroList.append(hero("Ursa"))
	heroList.append(hero("Vengeful Spirit"))
	heroList.append(hero("Venomancer"))
	heroList.append(hero("Viper"))
	heroList.append(hero("Weaver"))
	
	heroList.append(hero("Ancient Apparition"))
	heroList.append(hero("Bane"))
	heroList.append(hero("Batrider"))
	heroList.append(hero("Chen"))
	heroList.append(hero("Crystal Maiden"))
	heroList.append(hero("Dark Seer"))
	heroList.append(hero("Dark Willow"))
	heroList.append(hero("Dazzle"))
	heroList.append(hero("Death Prophet"))
	heroList.append(hero("Disruptor"))
	heroList.append(hero("Enchantress"))
	heroList.append(hero("Enigma"))
	heroList.append(hero("Grimstroke"))
	heroList.append(hero("Invoker"))
	heroList.append(hero("Jakiro"))
	heroList.append(hero("Keeper of the Light"))
	heroList.append(hero("Leshrac"))
	heroList.append(hero("Lich"))
	heroList.append(hero("Lina"))
	heroList.append(hero("Lion"))
	heroList.append(hero("Nature's Prophet"))
	heroList.append(hero("Necrophos"))
	heroList.append(hero("Ogre Magi"))
	heroList.append(hero("Oracle"))
	heroList.append(hero("Outworld Devourer"))
	heroList.append(hero("Puck"))
	heroList.append(hero("Pugna"))
	heroList.append(hero("Queen of Pain"))
	heroList.append(hero("Rubick"))
	heroList.append(hero("Shadow Demon"))
	heroList.append(hero("Shadow Shaman"))
	heroList.append(hero("Silencer"))
	heroList.append(hero("Skywrath Mage"))
	heroList.append(hero("Storm Spirit"))
	heroList.append(hero("Techies"))
	heroList.append(hero("Tinker"))
	heroList.append(hero("Visage"))
	heroList.append(hero("Warlock"))
	heroList.append(hero("Windranger"))
	heroList.append(hero("Winter Wyvern"))
	heroList.append(hero("Witch Doctor"))
	heroList.append(hero("Zeus"))
	
	hero_one = random.choice(heroList)
	hero_two = random.choice(heroList)
	while(hero_one == hero_two):
		hero_two = random.choice(heroList)
	
	
	print("HERO 1:")
	print("---------------------------")
	print(hero_one.name + " | " + hero_one.role)
	print("---------------------------\n\n")
	
	print("HERO 2:")
	print("---------------------------")
	print(hero_two.name + " | " + hero_two.role)
	print("---------------------------\n\n")
	
start()